[package]
name = "aom-av1-sys"
version = "0.1.0"
authors = ["Damezuma <qweads12@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "aom"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
